### ISSUE TITLE
calculateSummary, plotCellCounts fun not found

### ISSUE THREAD

**Issue by mohamadmilad** [BodenmillerGroup/imcRtools#13]
Hello, I installed imcRtools from github "devtools::install_github("BodenmillerGroup/imcRtools")", but I cannot find calculateSummary, plotCellCounts funtions. do you have any idea?

**Comment by nilseling** [comment]
Hi @mohamadmilad 

Sorry for this - I was not aware that `imcRtools` was in use. It is currently also heavily under development.
I removed these functions since there are better once exported by other packages.

For a `calculateSummary` replacement have a look at `scuttle::aggregateAcrossCells` [here](https://bioconductor.org/packages/release/bioc/vignettes/scuttle/inst/doc/overview.html#5_Aggregation_across_groups_or_clusters). By default, `aggregateAcrossCells` will sum the counts within groups of cells but you can choose a different statistic (e.g. mean) by setting the `statistics` parameter.

For a `plotCellCounts` replacement have a look at the [dittoSeq](https://www.bioconductor.org/packages/release/bioc/html/dittoSeq.html) package. 

I hope that helps.

**Comment by mohamadmilad** [comment]
Thank you for the reply. those are helpful, but I am running some codes which were developed by those functions and I need to reproduce the same result.
Is there any way that I can have access to imcRtools last version with those functions?  maybe if you could give me just .tgz file I can install it locally.

**Comment by nilseling** [comment]
Ah, alright, then please install the old version with:

`devtools::install_github("BodenmillerGroup/imcRtools", ref = "v0.2.0")`

**Comment by mohamadmilad** [comment]
Thank you!
